### ISSUE TITLE
redeem is leaving xSushi behind

### ISSUE THREAD

**Issue by asselstine** [steffenix/sushi-pooltogether#9]
Yield Source doesn't seem to be functioning correctly:

See this [mainnet tx](https://etherscan.io/address/0x42ef801e50d7491cf1b812e4d8ac44763e1cf97c)

xSushi are being left behind in the Yield Source.

Looks like this needs more testing

**Comment by steffenix** [comment]
Ok I will have to understand what has been done.

**Comment by steffenix** [comment]
The yield source owns the xSushi
<img width="514" alt="image" src="https://user-images.githubusercontent.com/2143646/112550747-25a8f880-8dc0-11eb-86d0-ac8d667e6af6.png">

**Comment by asselstine** [comment]
There is a problem with the `balanceOfToken` function it seems.

The Prize Pool address is 0x6FE3103A51196687b464A09287d2A3dCc674CB67.

`balanceOfToken('0x6FE3103A51196687b464A09287d2A3dCc674CB67')` returns 531503061, which is only 0.000000000531503061 Sushi.  However, the contract holds at least a few dollars in xSushi.

Something is wrong with the balanceOf function

**Comment by steffenix** [comment]
I found out some issues with the test that I am fixing now and will look at the contract afterward.

**Comment by steffenix** [comment]
Root cause found and fixed, adding more tests.

**Comment by steffenix** [comment]
Fix is one:
https://github.com/steffenix/sushi-pooltogether/commit/0f32cf2d0fc2d56b1594078a8ac63a23f3520fa1#diff-b838a3df13ede54c16493574db0b79705ccc08e5faa540d66e776c90c724d8feR70

The rest of the changes are copy-pasting the code from the Interface to make sure the doc matches.

**Comment by steffenix** [comment]
@asselstine 

I have deposited funds on the sushiBar to simulate mainnet, and make sure the root cause of the issues is solved.

Then made a deposit https://kovan.etherscan.io/tx/0x0141b891117ea3ca22048d9c6750de03da0bdea02bba28440376feaaa2a07826

I have then withdrawInstantlyFrom https://kovan.etherscan.io/tx/0xd690dc975e66bc39230a34bf40786589da3fc62b858544c6f11cd37bc2661aa8 all the 998 sushi were returned.

There is no stuck xSushi on the yield source https://kovan.etherscan.io/address/0x559aa5568543678793fa3d4a839815e68e183d5c

**Comment by steffenix** [comment]
The big mistake was the tests weren't properly asserting thing because comparing BigNumbers requires more than just a ==

**Comment by steffenix** [comment]
@asselstine
